### ISSUE TITLE
 Premature return to prompt when running "sleep 1 & sleep 3"

### ISSUE THREAD

**Issue by dariusbaker** [dariusbaker/murdoch-ict374-assignment-2#21]
`sleep 1 & sleep 3` should "disable" the prompt for 3 seconds but instead the first `sleep 1` activates the prompt after termination.

**Comment by squareTop** [comment]
which test case is this?
We tried `test_background()`, `test_combination()` and `test_sequential()` all working correctly.

**Comment by dariusbaker** [comment]
There is no test case for this. To see the error I described, run `sleep 1 & sleep 3`.

Expected behaviour:
```
% sleep 1 & sleep 3
// the prompt (%) shouldn't show until 3 seconds later
%
```

Actual behaviour:
```
% sleep 1 & sleep 3
%
// the prompt (%) shows after "sleep 1" terminates, which is incorrect
```

You can also run the command in your normal terminal to see what I mean.
